### ISSUE TITLE
Plugin saving and loading into the Battle Processing System

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LegendaryFrailty#67]
its preferrable if some form of auto-saving exists
its also a choice we could cut normal saving and only have auto saving if we wanted to punish the players for dying in some way

**Comment by tomizechsterson** [comment]
By default the game allows saving anywhere. Can this replace the auto-saving, or do we want to disable the save anywhere feature and force the user to rely on auto-saves?

**Comment by ZavixDragon** [comment]
So thats a tough call auto-saving seems like a good feature and then we might use save points instead of allowing in the menu, its definitely a design decision that will have to be made
