### ISSUE TITLE
Intro cutscene showing off your rise to power

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LegendaryFrailty#76]

**Comment by SilasReinagel** [comment]
Black Screen
----------------------------------------------------------------
This is the story of a man who became a legend.

His name is Anselm.
----------------------------------------------------------------


Library Scene
----------------------------------------------------------------
He dedicated his formative years to study...

Knowledge poured into his mind as fast as he could take it into
----------------------------------------------------------------

Meditation Scene
----------------------------------------------------------------
His days were filled with meditation...

The secrets of the universe opened themselves to him.
----------------------------------------------------------------

Dojo Scene
----------------------------------------------------------------
Spending long hours daily, practicing with his sensei...

He trained his body to be a weapon, mastering the staff. 
----------------------------------------------------------------

Dimensions Scene
----------------------------------------------------------------
The laws of physics tantalized and challenged him.

Accumulating his training, he studied Dimensional Magic.
----------------------------------------------------------------

Countryside Scene
----------------------------------------------------------------
With his preparations complete, Anselm sets out...

He wishes to become the prime guardian of the Water Goddess, Juturna
----------------------------------------------------------------
